# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 133c033284115c27636f8bc285a1e613eacf3adb6fb24e870494a8eff3b518cfbbbdde551881ce31a41a67744877a27e4fe808ae3b58f4cffa97156671b6d377

test:
  secret_key_base: c87b4595b805fc9af8f88de2ef6cce480c431c1591584ec56048ce8a76a8859566391d79a9ef6313fa3f1e57adda9e5353f07257fbd03fecb8d4a610dfe5bb49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
